---
- name: "Destroy environment"
  ec2:
    key_name: "e2essh-{{runId}}"
    region: us-east-2
    group: e2e
    image: '{{instance_meta.image}}'
    instance_tags:
      Name: "e2e-{{instance_meta.label}}-{{runId}}"
    exact_count: 0
    count_tag:
      Name: "e2e-{{instance_meta.label}}-{{runId}}"
  tags:
    - destroy
  async: 45
  poll: 0

- name: "Delete AWS keypair"
  ec2_key:
    region: us-east-2
    name: "e2essh-{{runId}}"
    state: absent
  tags:
    - destroy
  async: 45
  poll: 0

- name: Clear out instance inventory
  become: no
  copy:
    content: "[{{name}}]\n"
    dest: "{{workspace}}/.ci/ansible/inventory/{{name}}"
  loop:
    - fleet-amd64
    - fleet-arm64
    - stack
    - kubernetes-autodiscover
    - helm
  loop_control:
    loop_var: name
  tags:
    - destroy
