---
SUITES:
  - suite: "fleet"
    scenarios:
      - name: "Fleet"
        tags: "fleet_mode_agent"
        platforms:
          - labels: "fleet-arm64"
          - labels: "fleet-amd64"
      - name: "Integrations"
        tags: "integrations"
        platforms:
          - labels: "fleet-arm64"
          - labels: "fleet-amd64"
      - name: "APM Integration"
        tags: "apm_server"
        platforms:
          - labels: "fleet-amd64"
            provider: "elastic-package"
      - name: "Linux Integration"
        tags: "linux_integration"
        platforms:
          - labels: "fleet-arm64"
          - labels: "fleet-amd64"
      - name: "Permissions Output change"
        tags: "permission_change"
        platforms:
          - labels: "fleet-arm64"
          - labels: "fleet-amd64"
      - name: "Policies"
        tags: "policies"
        platforms:
          - labels: "fleet-arm64"
          - labels: "fleet-amd64"
      - name: "System Integration"
        tags: "system_integration"
        platforms:
          - labels: "fleet-arm64"
          - labels: "fleet-amd64"
      - name: "Stand-alone"
        tags: "stand_alone_agent"
        platforms:
          - labels: "fleet-amd64"
            provider: "elastic-package"
      - name: "Backend Processes"
        tags: "backend_processes"
        platforms:
          - labels: "fleet-arm64"
          - labels: "fleet-amd64"
      - name: "Beats Background Processes"
        tags: "running_on_beats"
        platforms:
          - labels: "fleet-arm64"
          - labels: "fleet-amd64"
      - name: "Preconfigured Policies"
        tags: "preconfigured_policies"
        platforms:
          - labels: "fleet-amd64"
            provider: "elastic-package"
