---
MACHINES:
  stack: 1
  helm: 3
  fleet_arm64: 6
  fleet_amd64: 6
  fleet_elastic_pkg: 2
  kubernetes_autodiscover: 4

SUITES:
  - suite: "helm"
    scenarios:
      - name: "APM Server"
        tags: "apm-server"
        platforms:
          - labels: "helm"
      - name: "Filebeat"
        tags: "filebeat"
        platforms:
          - labels: "helm"
      - name: "Metricbeat"
        tags: "metricbeat"
        platforms:
          - labels: "helm"
  - suite: "fleet"
    scenarios:
      - name: "Fleet"
        tags: "fleet_mode_agent"
        platforms:
          - labels: "fleet_arm64"
          - labels: "fleet_amd64"
      - name: "Integrations"
        tags: "integrations"
        platforms:
          - labels: "fleet_arm64"
          - labels: "fleet_amd64"
      - name: "APM Integration"
        tags: "apm_server"
        platforms:
          - labels: "fleet_elastic_pkg"
      - name: "Linux Integration"
        tags: "linux_integration"
        platforms:
          - labels: "fleet_arm64"
          - labels: "fleet_amd64"
      # - name: "Permissions Output change"
      #   tags: "permission_change"
      #   platforms:
      #     - labels: "fleet_arm64"
      #     - labels: "fleet_amd64"
      - name: "System Integration"
        tags: "system_integration"
        platforms:
          - labels: "fleet_arm64"
          - labels: "fleet_amd64"
      - name: "Stand-alone"
        tags: "stand_alone_agent"
        platforms:
          - labels: "fleet_elastic_pkg"
      - name: "Backend Processes"
        tags: "backend_processes"
        platforms:
          - labels: "fleet_arm64"
          - labels: "fleet_amd64"
      - name: "Beats Background Processes"
        tags: "running_on_beats"
        platforms:
          - labels: "fleet_arm64"
          - labels: "fleet_amd64"
  - suite: "kubernetes-autodiscover"
    scenarios:
      - name: "kubernetes autodiscover with elastic-agent"
        tags: "elastic-agent"
        platforms:
          - labels: "kubernetes_autodiscover"
      - name: "kubernetes autodiscover with filebeat"
        tags: "filebeat"
        platforms:
          - labels: "kubernetes_autodiscover"
      - name: "kubernetes autodiscover with heartbeat"
        tags: "heartbeat"
        platforms:
          - labels: "kubernetes_autodiscover"
      - name: "kubernetes autodiscover with metricbeat"
        tags: "metricbeat"
        platforms:
          - labels: "kubernetes_autodiscover"
