- name: Create test environment
  hosts: localhost
  gather_facts: no
  vars:
      ansible_user: ubuntu
  tasks:
  - name: Setup nodes
    include_tasks: tasks/runners.yml
    loop:
      - {label: "stack", image: "ami-0629230e074c580f2", instance_type: "c5.4xlarge", count: 1}
      - {label: "fleet-amd64", image: "ami-0629230e074c580f2", instance_type: "c5.2xlarge", count: 11}
      - {label: "fleet-arm64", image: "ami-03b47d2d727e13114", instance_type: "a1.large", count: 11}
      - {label: "kubernetes-autodiscover", image: "ami-0629230e074c580f2", instance_type: "c5.2xlarge", count: 4}
      - {label: "helm", image: "ami-0629230e074c580f2", instance_type: "c5.2xlarge", count: 3}
    loop_control:
      loop_var: instance_meta
    tags:
      - provision-stack

- name: Teardown environment
  hosts: localhost
  gather_facts: no
  vars:
      ansible_user: ubuntu
  tasks:
  - name: Teardown Test Runners (AWS)
    include_tasks: tasks/teardown.yml
    loop:
      - {label: "stack", image: "ami-0629230e074c580f2", instance_type: "c5.4xlarge", count: 1}
      - {label: "fleet-amd64", image: "ami-0629230e074c580f2", instance_type: "c5.2xlarge", count: 11}
      - {label: "fleet-arm64", image: "ami-03b47d2d727e13114", instance_type: "a1.large", count: 11}
      - {label: "kubernetes-autodiscover", image: "ami-0629230e074c580f2", instance_type: "c5.2xlarge", count: 4}
      - {label: "helm", image: "ami-0629230e074c580f2", instance_type: "c5.2xlarge", count: 3}
    loop_control:
      loop_var: instance_meta
    tags:
      - destroy

- name: Wait for SSH
  hosts:
    - stack
    - kubernetes-autodiscover
    - helm
    - fleet-amd64
    - fleet-arm64
  connection: ssh
  vars:
      ansible_user: ubuntu
  tags:
    - setup
  tasks:
    - name: Testing connection
      include_tasks: tasks/wait_for_ssh.yml

- name: Manage stack instance
  hosts: stack
  connection: ssh
  become: True
  tags:
    - setup
  roles:
    - role: geerlingguy.docker
    - role: andrewrothstein.kubectl
    - role: andrewrothstein.kind
    - role: andrewrothstein.go
      vars:
        go_ver: 1.16.3
  vars:
    ansible_user: ubuntu
  tasks:
  - name: Wait for SSH
    include_tasks: tasks/wait_for_ssh.yml
    tags:
      - setup

  - name: Create environment file
    become: no
    local_action:
      module: copy
      dest: "{{workspace}}/.env"
      content: |
        export OP_LOG_LEVEL=TRACE
        export LOG_LEVEL=TRACE
        export ELASTICSEARCH_URL=http://{{inventory_hostname}}:9200
        export ELASTICSEARCH_PASSWORD=changeme
        export KIBANA_PASSWORD=changeme
        export KIBANA_URL=http://{{inventory_hostname}}:5601
        export FLEET_URL=http://{{inventory_hostname}}:8220
        export SKIP_PULL=1
    tags:
      - setup

  - name: Setup source code
    include_tasks: tasks/copy_test_files.yml
    tags:
      - setup

  - name: Start stack
    shell: |
      sed -i '' -e 's,http://elasticsearch,http://{{inventory_hostname}},g' /home/{{ansible_user}}/e2e-testing/cli/config/compose/profiles/fleet/default/kibana.config.yml
      sed -i '' -e 's,http://fleet-server,http://{{inventory_hostname}},g' /home/{{ansible_user}}/e2e-testing/cli/config/compose/profiles/fleet/default/kibana.config.yml
      sed -i '' -e 's,http://package-registry:8080,https://epr-staging.elastic.co,g' /home/{{ansible_user}}/e2e-testing/cli/config/compose/profiles/fleet/default/kibana.config.yml
      sudo docker-compose -f /home/{{ansible_user}}/e2e-testing/cli/config/compose/profiles/fleet/docker-compose.yml up -d
    tags:
      - setup

- name: Manage runner instances
  hosts:
    - kubernetes-autodiscover
    - helm
    - fleet-amd64
    - fleet-arm64
  connection: ssh
  become: True
  tags:
    - setup
  roles:
    - role: geerlingguy.docker
      when: "'kubernetes-autodiscover' in group_names or 'helm' in group_names or 'fleet-amd64' in group_names"
    - role: andrewrothstein.kubectl
      when: "'kubernetes-autodiscover' in group_names or 'helm' in group_names"
    - role: andrewrothstein.kind
      when: "'kubernetes-autodiscover' in group_names or 'helm' in group_names"
    - role: andrewrothstein.kubernetes-helm
      when: "'kubernetes-autodiscover' in group_names or 'helm' in group_names"
    - role: andrewrothstein.go
      vars:
        go_ver: 1.16.3
  vars:
    ansible_user: ubuntu
  tasks:
  - name: Install deps
    include_tasks: tasks/install_deps.yml
    tags:
      - setup

  - name: Setup source code
    include_tasks: tasks/copy_test_files.yml
    tags:
      - setup

  - name: Configure test script
    include_tasks: tasks/setup_test_script.yml
    tags:
      - setup
