- name: Create test environment
  hosts: localhost
  gather_facts: no
  vars:
      ansible_user: ubuntu
  tasks:
  - name: Read e2e spec
    include_vars:
      file: "{{workspace}}/.ci/.e2e-tests.yaml"
      name: machineMeta
    tags:
      - provision-stack

  - name: Setup nodes
    include_tasks: tasks/runners.yml
    loop:
      - {label: "stack", image: "ami-0629230e074c580f2", instance_type: "c5.4xlarge", count: "{{machineMeta.MACHINES.stack}}"}
      - {label: "fleet_amd64", image: "ami-0629230e074c580f2", instance_type: "c5.2xlarge", count: "{{machineMeta.MACHINES.fleet_amd64}}"}
      - {label: "fleet_elastic_pkg", image: "ami-0629230e074c580f2", instance_type: "c5.2xlarge", count: "{{machineMeta.MACHINES.fleet_elastic_pkg}}"}
      - {label: "fleet_arm64", image: "ami-03b47d2d727e13114", instance_type: "a1.large", count: "{{machineMeta.MACHINES.fleet_arm64}}"}
      - {label: "kubernetes_autodiscover", image: "ami-0629230e074c580f2", instance_type: "c5.2xlarge", count: "{{machineMeta.MACHINES.kubernetes_autodiscover}}"}
      - {label: "helm", image: "ami-0629230e074c580f2", instance_type: "c5.2xlarge", count: "{{machineMeta.MACHINES.helm}}"}
    loop_control:
      loop_var: instance_meta
    tags:
      - provision-stack

- name: Teardown environment
  hosts: localhost
  gather_facts: no
  vars:
      ansible_user: ubuntu
  tasks:
  - name: Read e2e spec
    include_vars:
      file: "{{workspace}}/.ci/.e2e-tests.yaml"
      name: machineMeta
    tags:
      - destroy
  - name: Teardown Test Runners (AWS)
    include_tasks: tasks/teardown.yml
    loop:
      - {label: "stack", image: "ami-0629230e074c580f2", instance_type: "c5.4xlarge", count: "{{machineMeta.MACHINES.stack}}"}
      - {label: "fleet_amd64", image: "ami-0629230e074c580f2", instance_type: "c5.2xlarge", count: "{{machineMeta.MACHINES.fleet_amd64}}"}
      - {label: "fleet_elastic_pkg", image: "ami-0629230e074c580f2", instance_type: "c5.2xlarge", count: "{{machineMeta.MACHINES.fleet_elastic_pkg}}"}
      - {label: "fleet_arm64", image: "ami-03b47d2d727e13114", instance_type: "a1.large", count: "{{machineMeta.MACHINES.fleet_arm64}}"}
      - {label: "kubernetes_autodiscover", image: "ami-0629230e074c580f2", instance_type: "c5.2xlarge", count: "{{machineMeta.MACHINES.kubernetes_autodiscover}}"}
      - {label: "helm", image: "ami-0629230e074c580f2", instance_type: "c5.2xlarge", count: "{{machineMeta.MACHINES.helm}}"}
    loop_control:
      loop_var: instance_meta
    tags:
      - destroy

- name: Wait for SSH
  hosts:
    - stack
    - kubernetes_autodiscover
    - helm
    - fleet_amd64
    - fleet_arm64
    - fleet_elastic_pkg
  connection: ssh
  vars:
      ansible_user: ubuntu
  tags:
    - setup
  tasks:
    - name: Testing connection
      include_tasks: tasks/wait_for_ssh.yml

- name: Manage stack instance
  hosts: stack
  connection: ssh
  become: True
  tags:
    - setup
  roles:
    - role: geerlingguy.docker
    - role: andrewrothstein.kubectl
    - role: andrewrothstein.kind
    - role: gantsign.golang
      vars:
        golang_version: 1.16.3
  vars:
    ansible_user: ubuntu
  tasks:
  - name: Wait for SSH
    include_tasks: tasks/wait_for_ssh.yml
    tags:
      - setup

  - name: Create environment file
    become: no
    local_action:
      module: copy
      dest: "{{workspace}}/.env"
      content: |
        export OP_LOG_LEVEL=TRACE
        export LOG_LEVEL=TRACE
    tags:
      - setup

  - name: Setup source code
    include_tasks: tasks/copy_test_files.yml
    tags:
      - setup

  - name: Start stack
    shell: |
      sed -i '' -e 's,http://elasticsearch,http://{{inventory_hostname}},g' /home/{{ansible_user}}/e2e-testing/cli/config/compose/profiles/fleet/default/kibana.config.yml
      sed -i '' -e 's,http://fleet-server,http://{{inventory_hostname}},g' /home/{{ansible_user}}/e2e-testing/cli/config/compose/profiles/fleet/default/kibana.config.yml
      sed -i '' -e 's,http://package-registry:8080,https://epr-staging.elastic.co,g' /home/{{ansible_user}}/e2e-testing/cli/config/compose/profiles/fleet/default/kibana.config.yml
      sudo docker-compose -f /home/{{ansible_user}}/e2e-testing/cli/config/compose/profiles/fleet/docker-compose.yml up -d
    tags:
      - setup

- name: Manage runner instances
  hosts:
    - kubernetes_autodiscover
    - helm
    - fleet_amd64
    - fleet_arm64
    - fleet_elastic_pkg
  connection: ssh
  become: True
  tags:
    - setup
  roles:
    - role: geerlingguy.docker
      when: "'kubernetes_autodiscover' in group_names or 'helm' in group_names or 'fleet_amd64' in group_names or 'fleet_elastic_pkg' in group_names"
    - role: andrewrothstein.kubectl
      when: "'kubernetes_autodiscover' in group_names or 'helm' in group_names"
    - role: andrewrothstein.kind
      when: "'kubernetes_autodiscover' in group_names or 'helm' in group_names"
    - role: geerlingguy.helm
      when: "'kubernetes_autodiscover' in group_names or 'helm' in group_names"
    - role: gantsign.golang
      vars:
        golang_version: 1.16.3
  vars:
    ansible_user: ubuntu
  tasks:
  - name: Install deps
    include_tasks: tasks/install_deps.yml
    tags:
      - setup

  - name: Setup source code
    include_tasks: tasks/copy_test_files.yml
    tags:
      - setup

  - name: Configure test script
    include_tasks: tasks/setup_test_script.yml
    tags:
      - setup
